// 1. Tipos de Next.js
import type { Metadata } from "next";

// 2. Fuentes de Next.js
import { Geist, Geist_Mono } from "next/font/google";

// 3. Librerías externas
import { ClerkProvider } from "@clerk/nextjs";

// 4. Estilos globales
import "./globals.css";

// 5. Componentes globales
import Sidebar from "@/components/sidebar/sidebar";

// 6. Providers
import ReactQueryProvider from "@/providers/query-client";
import ToasterProvider from "@/providers/toast-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <ReactQueryProvider>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <div className="h-screen flex flex-col">
              <div className="flex flex-1 overflow-hidden">
                <ToasterProvider />
                <Sidebar />
                <main className="flex-1 overflow-y-auto">
                  {children}
                </main>
              </div>
            </div>
          </body>
        </ReactQueryProvider>
      </ClerkProvider>
    </html>

  );
}
