// 1. Tipos de Next.js
import type { Metadata } from "next";

// 2. Fuentes de Next.js
import { Geist, Geist_Mono } from "next/font/google";

// 3. Librerías externas
import { ClerkProvider } from "@clerk/nextjs";

// 4. Estilos globales
import "./globals.css";

// 6. Providers
import ReactQueryProvider from "@/providers/query-client";
import ToasterProvider from "@/providers/toast-provider";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppBreadcrumbs } from "@/components/app-breadcrumbs";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@radix-ui/react-select";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <ReactQueryProvider>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <div className="h-screen flex flex-col">
              <div className="overflow-hidden">
                <ToasterProvider />
                <SidebarProvider>
                  <AppSidebar />
                  <main className="w-full">
                    <SidebarInset>
                      <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
                        <SidebarTrigger className="-ml-1" />
                        <Separator
                          className="mr-2 data-[orientation=vertical]:h-4"
                        />
                        <AppBreadcrumbs />
                      </header>
                    </SidebarInset>
                    {children}
                  </main>
                </SidebarProvider>
              </div>
            </div>
          </body>
        </ReactQueryProvider>
      </ClerkProvider>
    </html >

  );
}
